Repository python-graphblas/python-graphblas, pull requests merged in 2023-03, with the labels that each got.

#413 Fix right panel visibility overlap issue
  docs/_static/custom.css
  docs/api_reference/collections.rst
  docs/api_reference/exceptions.rst
  docs/api_reference/index.rst
  docs/api_reference/io.rst
  docs/api_reference/operators.rst
Labels: documentation

#418 Fix infix expression `_value` and `_expr` usage
  .pre-commit-config.yaml
  environment.yml
  graphblas/core/expr.py
  graphblas/core/formatting.py
  graphblas/core/infix.py
  graphblas/core/recorder.py
  graphblas/tests/test_infix.py
  pyproject.toml
Labels: bug

#419 Improve import times
  graphblas/core/operator.py
  graphblas/monoid/numpy.py
Labels: regression, performance

#420 Split operator.py into multiple files
  .flake8
  .github/workflows/test_and_build.yml
  .pre-commit-config.yaml
  dev-requirements.txt
  environment.yml
  graphblas/agg/__init__.py
  graphblas/agg/ss.py
  graphblas/binary/numpy.py
  graphblas/core/agg.py
  graphblas/core/operator.py
  graphblas/core/operator/__init__.py
  graphblas/core/operator/agg.py
  graphblas/core/operator/base.py
  graphblas/core/operator/binary.py
  graphblas/core/operator/indexunary.py
  graphblas/core/operator/monoid.py
  graphblas/core/operator/select.py
  graphblas/core/operator/semiring.py
  graphblas/core/operator/unary.py
  graphblas/core/operator/utils.py
  graphblas/monoid/numpy.py
  graphblas/semiring/numpy.py
  graphblas/tests/pickle1-vanilla.pkl
  graphblas/tests/pickle1.pkl
  graphblas/tests/pickle2-vanilla.pkl
  graphblas/tests/pickle2.pkl
  graphblas/tests/pickle3-vanilla.pkl
  graphblas/tests/pickle3.pkl
  graphblas/tests/test_core.py
  graphblas/tests/test_op.py
  graphblas/unary/numpy.py
  pyproject.toml
  scripts/check_versions.sh
  scripts/create_pickle.py
  scripts/test_imports.sh
Labels: hygiene
